filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
build:
  environment:
    php: '7.0'
    postgresql: false
    redis: false
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=.coverage.tmp'
        coverage:
          file: '.coverage.tmp'
          format: 'clover'
coding_style:
  php:
    spaces:
      before_parentheses:
        closure_definition: true
      around_operators:
        concatenation: true
      other:
        after_type_cast: false